export const genderOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];

export const campusOptions = [
  { value: "ojo", label: "Ojo campus (main)" },
  { value: "epe", label: "Epe campus" },
  { value: "ikj", label: "Ikeja campus" },
];

export const facultyOptions = [
  { value: "art", label: "Arts" },
  { value: "edu", label: "Education" },
  { value: "eng", label: "Engineering" },
  { value: "law", label: "Law" },
  { value: "sci", label: "Science" },
  { value: "fss", label: "Social Science" },
  { value: "mass", label: "Mass communication" },
  { value: "fms", label: "Management Science" },
  { value: "bms", label: "Basic Medical Sciences" },
  { value: "cs", label: "Clinical Sciences" },
  { value: "den", label: "Dentistry" },
  { value: "env", label: "Environmental Sciences" },
  { value: "agric", label: "Agriculture" },
  { value: "tran", label: "Transport and logistics" },
  { value: "computing", label: "Computing and Information Technology" },
  { value: "lib", label: "Library" },
  { value: "tour", label: "Tourism" },
];

export const departmentOptions = [
  { value: "acc", label: "Accounting" },
  { value: "aerona", label: "Aeronautics" },
  { value: "aerosp", label: "Aerospace" },
  { value: "agriceco", label: "Agricultural Economics" },
  { value: "agric", label: "Agriculture" },
  { value: "anas", label: "Anasthesia" },
  { value: "anato", label: "Anatomy" },
  { value: "banfi", label: "Banking And Finance" },
  { value: "behmed", label: "Behavioural Medicine" },
  { value: "bioch", label: "Biochemistry" },
  { value: "bot", label: "Botany" },
  { value: "broca", label: "Broadcasting" },
  { value: "busad", label: "Business Administration" },
  { value: "busla", label: "Business Law" },
  { value: "chmen", label: "Chemical Engineering" },
  { value: "chmpa", label: "Chemical Pathology" },
  { value: "chem", label: "Chemistry" },
  { value: "cdh", label: "Child Dental Health" },
  { value: "cde", label: "Collection Development" },
  { value: "comh", label: "Community Health" },
  { value: "csc", label: "Comp Science" },
  { value: "eco", label: "Economics" },
  { value: "efcp", label: "Educational Foundations" },
  { value: "edma", label: "Educational Management" },
  { value: "elco", label: "Electronics And Computer Eng" },
  { value: "eng", label: "English" },
  { value: "esma", label: "Estate Management" },
  { value: "fis", label: "Fisheries" },
  { value: "fola", label: "Foreign Languages" },
  { value: "geop", label: "Geography And Planning" },
  { value: "hbt", label: "Hematology And Blood Transfusion" },
  { value: "hir", label: "History And International Relations" },
  { value: "hki", label: "Human Kinetic" },
  { value: "indr", label: "Industrial Relations" },
  { value: "insu", label: "Insurance" },
  { value: "iil", label: "International And Islamic Law" },
  { value: "jou", label: "Journalism" },
  { value: "juil", label: "Jurisprudence And International Law" },
  { value: "las", label: "Lang Arts And Sci" },
  { value: "law", label: "Law" },
  { value: "libs", label: "Library And Information Science" },
  { value: "loga", label: "Local Government Administration" },
  { value: "mante", label: "Management Technology" },
  { value: "mark", label: "Marketing" },
  { value: "math", label: "Mathematics" },
  { value: "meceng", label: "Mechanical Engineering" },
  { value: "medbio", label: "Medical Biochemistry" },
  { value: "medlab", label: "Medical Laboratory Science" },
  { value: "medmic", label: "Medical Microbiology" },
  { value: "medi", label: "Medicine" },
  { value: "micro", label: "Microbiology" },
  { value: "mus", label: "Music" },
  { value: "nur", label: "Nursing" },
  { value: "obst", label: "Obstetrics And Gynaecology" },
  { value: "oramax", label: "Oral And Maxillofacial" },
  { value: "orapat", label: "Oral And Pathology" },
  { value: "patfo", label: "Pathology And Forensic" },
  { value: "pedhea", label: "Pediatrics And Child Health" },
  { value: "phar", label: "Pharmacology" },
  { value: "phil", label: "Philosophy" },
  { value: "phy", label: "Physics" },
  { value: "physi", label: "Physiology" },
  { value: "phyth", label: "Physiotherapy" },
  { value: "polsc", label: "Political Science" },
  { value: "posgra", label: "Post Graduate School" },
  { value: "preden", label: "Preventive Dentistry" },
  { value: "pubadm", label: "Public Administration" },
  { value: "puprla", label: "Public And Private Law" },
  { value: "pubre", label: "Public relations" },
  { value: "radgr", label: "Radiography" },
  { value: "radlo", label: "Radiology" },
  { value: "reaser", label: "Readers Services" },
  { value: "reli", label: "Religions" },
  { value: "resde", label: "Restirative Dentistry" },
  { value: "scitech", label: "Science And Tech" },
  { value: "scilab", label: "Science Laboratory Technology" },
  { value: "socio", label: "Sociology" },
  { value: "sur", label: "Surgery" },
  { value: "techse", label: "Technical Services" },
  { value: "theart", label: "Theatre Arts" },
  { value: "tranma", label: "Transport Management" },
  { value: "tranpl", label: "Transport Planning" },
  { value: "trante", label: "Transport Technology" },
  { value: "zoo", label: "Zoology" },
];

export const levelOptions = [
  { value: "100", label: "100L" },
  { value: "200", label: "200L" },
  { value: "300", label: "300L" },
  { value: "400", label: "400L" },
  { value: "500", label: "500L" },
];

export const currentStepFields = {
  1: ["fullname", "email", "gender"],
  2: ["matricNo", "campus", "faculty", "department", "level"],
  3: [
    "whatsappNumber",
    "callingNumber",
    "address",
    "guardianName",
    "guardianNumber",
  ],
  4: ["username", "password", "confirmPassword"],
} as const;

export const stepsDescriptions = [
  "Personal",
  "Academic",
  "Contact",
  "Additional",
];
